In [66]:
import numpy as np
a = np.array([1,2,3])
b = np.array((1,2,3))
print(a)
print(b)

[1 2 3]
[1 2 3]


In [67]:
b[1]=4

In [68]:
b

array([1, 4, 3])

In [69]:
c = np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [70]:
c[0]

array([1, 2, 3])

In [71]:
c[1]

array([4, 5, 6])

In [72]:
c[0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
c[:1]

array([[1, 2, 3]])

In [74]:
a[0]

1

In [75]:
a[1]

2

In [76]:
a[1:2]

array([2])

In [77]:
a[1:3]

array([2, 3])

In [78]:
a[1:]

array([2, 3])

In [79]:
a = np.zeros((3,4))
#np.zeros((row,column))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [80]:
#np.arange(startnum,endnum,interval)
#startnum till endnum - interval
a = np.arange(10,25,5)

In [81]:
print(a)

[10 15 20]


In [82]:
#np.linspace(startnum,endnum,numberofpoints)
b = np.linspace(5,6,10)
print(b)

[5.         5.11111111 5.22222222 5.33333333 5.44444444 5.55555556
 5.66666667 5.77777778 5.88888889 6.        ]


In [83]:
import numpy as np
#np.full((rownum,colnum),numbertofill)
c = np.full((3,4),5)
print(c)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [84]:
import numpy as np
d = np.random.random((3,4))
print(d)

[[0.70370402 0.43740735 0.87658638 0.69396047]
 [0.90729525 0.57507446 0.69004369 0.99078078]
 [0.84001818 0.97754927 0.20991888 0.27521776]]


In [85]:
a = np.array([[1,2,3],[4,5,6]])

In [86]:
print(a)
#np.array.shape return tuple (rownum,colnum)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [87]:
a.shape = (3,2)
print(a.shape[0])
print(a.shape[1])
#returns the number of dimensions of the array
print(a.ndim)
print(a)

3
2
2
[[1 2]
 [3 4]
 [5 6]]


In [88]:
#np.arange(numberofpointsneeded)
#will place the numbers between 0 till that number
a = np.arange(24)

In [89]:
a.size

24

In [90]:
a.dtype

dtype('int32')

In [91]:
b = np.linspace(5,7,11)
print(b)
print(b.dtype)

[5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7. ]
float64


In [92]:
a = np.array([5,10])
print(a)
np.sum(a)

[ 5 10]


15

In [93]:
b = np.array([2,3])
print(b)
print(np.sum([a,b]))
print(np.subtract(a,b))

[2 3]
20
[3 7]


In [94]:
np.sum([[a],[b]], axis=1)

array([[ 5, 10],
       [ 2,  3]])

In [95]:
print(a)
print(b)

[ 5 10]
[2 3]


In [96]:
print(np.divide(a,b))

[2.5        3.33333333]


In [97]:
print(np.multiply(a,b))

[10 30]


In [98]:
print(np.log(a))

[1.60943791 2.30258509]


In [99]:
print(np.cos(a))

[ 0.28366219 -0.83907153]


In [100]:
print(np.sin(a))

[-0.95892427 -0.54402111]


In [101]:
print(np.sqrt(a))

[2.23606798 3.16227766]


In [102]:
a = [1,2,3]
b = [3,2,3]
print(np.equal(a,b))
print(np.array_equal(a,b))

[False  True  True]
False


In [103]:
a = np.array([[1,2,3],[4,5,6]])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.std(a))
print(np.median(a))
print(np.corrcoef(a))

21
1
6
3.5
1.707825127659933
3.5
[[1. 1.]
 [1. 1.]]


In [104]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([3,4,5])
print(a)
print(b)
print(np.subtract(a,b))

[[1 2 3]
 [4 5 6]]
[3 4 5]
[[-2 -2 -2]
 [ 1  1  1]]


In [105]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a[0])
print(a[:1])
print(a[:,1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[[1 2 3]]
[[2 3]
 [5 6]
 [8 9]]


In [106]:
print(a[:2,2:])

[[3]
 [6]]


In [107]:
a = np.array([1,2,3])
print(a)
b = np.array([3,4,5])
print(b)
#print(np.concatenate([a,b],axis=0))
#print(np.concatenate([a,b],axis=1))

[1 2 3]
[3 4 5]


In [108]:
np.stack((a,b),axis=0)

array([[1, 2, 3],
       [3, 4, 5]])

In [109]:
np.stack((a,b),axis=1)

array([[1, 3],
       [2, 4],
       [3, 5]])

In [110]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[2,3,4],[5,6,7]])
print("A Matrix")
print(a)
print("B Matrix")
print(b)
print("Horizontal Stack")
print(np.hstack((a,b)))
print("Horizontal Concat")
print(np.concatenate((a,b),axis=0))
print("Vertical Stack")
print(np.vstack((a,b)))
print("Vertical Concat")
print(np.concatenate((a,b),axis=1))
print("Column Stack")
print(np.column_stack((a,b)))

A Matrix
[[1 2 3]
 [4 5 6]]
B Matrix
[[2 3 4]
 [5 6 7]]
Horizontal Stack
[[1 2 3 2 3 4]
 [4 5 6 5 6 7]]
Horizontal Concat
[[1 2 3]
 [4 5 6]
 [2 3 4]
 [5 6 7]]
Vertical Stack
[[1 2 3]
 [4 5 6]
 [2 3 4]
 [5 6 7]]
Vertical Concat
[[1 2 3 2 3 4]
 [4 5 6 5 6 7]]
Column Stack
[[1 2 3 2 3 4]
 [4 5 6 5 6 7]]


In [111]:
#np.split(array, index, axis)
#array=numpy array
#index=integer/list

In [112]:
print(a)
print(np.split(a,2,axis = 0))
print(np.split(a,3,axis = 1))

[[1 2 3]
 [4 5 6]]
[array([[1, 2, 3]]), array([[4, 5, 6]])]
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [113]:
print(np.split(a,[1,2],axis=0))

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32)]


In [114]:
a[:1]

array([[1, 2, 3]])

In [115]:
a[1:2]

array([[4, 5, 6]])

In [116]:
a[2:]

array([], shape=(0, 3), dtype=int32)

In [117]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
print(np.split(a,[1,2],axis=1))

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [119]:
a[:,:1]

array([[1],
       [4]])

In [120]:
a[:,2:]

array([[3],
       [6]])

In [132]:
#numpy v list: Memory size
import numpy as np
import sys

#define a list
l = range(1000)
print(l)
print("Size of a list: ",sys.getsizeof(1)*len(l))

#define a numpy array
a = np.arange(1000)
print("Size of an array: ",a.size*a.itemsize)

range(0, 1000)
Size of a list:  28000
Size of an array:  4000


In [138]:
#numpy vs list: Speed
import time
def using_List():
    t1 = time.time()#Starting/initial time
    X = range(10000)
    Y = range(10000)
    z = [X[i] + Y[i] for i in range(len(X))]
    return time.time() - t1

def using_Numpy():
    t1 = time.time()#Starting/initial time
    a = np.arange(100000)
    b = np.arange(100000)
    z = a + b #more convenient than a list
    return time.time() - t1
list_time = using_List()
numpy_time = using_Numpy()
print(list_time,numpy_time)
print("In this example Numpy is "+str(list_time/numpy_time)+" time faster than a list")

0.0019958019256591797 0.0009992122650146484
In this example Numpy is 1.9973753280839894 time faster than a list
